/*******************************************************************************
 * #%L
 * Armedia Caliente
 * %%
 * Copyright (C) 2013 - 2019 Armedia, LLC
 * %%
 * This file is part of the Caliente software.
 *
 * If the software was purchased under a paid Caliente license, the terms of
 * the paid license agreement will prevail.  Otherwise, the software is
 * provided under the following open source license terms:
 *
 * Caliente is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Caliente is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Caliente. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.01 at 11:04:18 AM CST
//

package com.armedia.caliente.cli.flat2db.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for dataSource.t complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="dataSource.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{http://www.armedia.com/ns/caliente/flat2db}properties.t"/>
 *         &lt;element name="startup" type="{http://www.armedia.com/ns/caliente/flat2db}sqlInitializerTasks.t" minOccurs="0"/>
 *         &lt;element name="on-insert" type="{http://www.armedia.com/ns/caliente/flat2db}sqlTasks.t" minOccurs="0"/>
 *         &lt;element name="on-error" type="{http://www.armedia.com/ns/caliente/flat2db}sqlTasks.t" minOccurs="0"/>
 *         &lt;element name="shutdown" type="{http://www.armedia.com/ns/caliente/flat2db}sqlInitializerTasks.t" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.armedia.com/ns/caliente/flat2db}id_string.t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataSource.t", propOrder = {
	"properties", "startup", "onInsert", "onError", "shutdown"
})
public class DataSourceT {

	@XmlElement(required = true)
	protected PropertiesT properties;
	protected SqlInitializerTasksT startup;
	@XmlElement(name = "on-insert")
	protected SqlTasksT onInsert;
	@XmlElement(name = "on-error")
	protected SqlTasksT onError;
	protected SqlInitializerTasksT shutdown;
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/**
	 * Gets the value of the properties property.
	 *
	 * @return possible object is {@link PropertiesT }
	 *
	 */
	public PropertiesT getProperties() {
		return this.properties;
	}

	/**
	 * Sets the value of the properties property.
	 *
	 * @param value
	 *            allowed object is {@link PropertiesT }
	 *
	 */
	public void setProperties(PropertiesT value) {
		this.properties = value;
	}

	/**
	 * Gets the value of the startup property.
	 *
	 * @return possible object is {@link SqlInitializerTasksT }
	 *
	 */
	public SqlInitializerTasksT getStartup() {
		return this.startup;
	}

	/**
	 * Sets the value of the startup property.
	 *
	 * @param value
	 *            allowed object is {@link SqlInitializerTasksT }
	 *
	 */
	public void setStartup(SqlInitializerTasksT value) {
		this.startup = value;
	}

	/**
	 * Gets the value of the onInsert property.
	 *
	 * @return possible object is {@link SqlTasksT }
	 *
	 */
	public SqlTasksT getOnInsert() {
		return this.onInsert;
	}

	/**
	 * Sets the value of the onInsert property.
	 *
	 * @param value
	 *            allowed object is {@link SqlTasksT }
	 *
	 */
	public void setOnInsert(SqlTasksT value) {
		this.onInsert = value;
	}

	/**
	 * Gets the value of the onError property.
	 *
	 * @return possible object is {@link SqlTasksT }
	 *
	 */
	public SqlTasksT getOnError() {
		return this.onError;
	}

	/**
	 * Sets the value of the onError property.
	 *
	 * @param value
	 *            allowed object is {@link SqlTasksT }
	 *
	 */
	public void setOnError(SqlTasksT value) {
		this.onError = value;
	}

	/**
	 * Gets the value of the shutdown property.
	 *
	 * @return possible object is {@link SqlInitializerTasksT }
	 *
	 */
	public SqlInitializerTasksT getShutdown() {
		return this.shutdown;
	}

	/**
	 * Sets the value of the shutdown property.
	 *
	 * @param value
	 *            allowed object is {@link SqlInitializerTasksT }
	 *
	 */
	public void setShutdown(SqlInitializerTasksT value) {
		this.shutdown = value;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setId(String value) {
		this.id = value;
	}

}
