/*******************************************************************************
 * #%L
 * Armedia Caliente
 * %%
 * Copyright (C) 2013 - 2019 Armedia, LLC
 * %%
 * This file is part of the Caliente software.
 *
 * If the software was purchased under a paid Caliente license, the terms of
 * the paid license agreement will prevail.  Otherwise, the software is
 * provided under the following open source license terms:
 *
 * Caliente is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Caliente is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Caliente. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.01 at 11:04:18 AM CST
//

package com.armedia.caliente.cli.flat2db.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for structure.t complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="structure.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.armedia.com/ns/caliente/flat2db}structureHeader.t" minOccurs="0"/>
 *         &lt;element name="range" type="{http://www.armedia.com/ns/caliente/flat2db}structureRange.t" minOccurs="0"/>
 *         &lt;element name="filter" type="{http://www.armedia.com/ns/caliente/flat2db}structureFilter.t" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.armedia.com/ns/caliente/flat2db}id_string.t" />
 *       &lt;attribute name="extends" type="{http://www.armedia.com/ns/caliente/flat2db}trimmed_string.t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "structure.t", propOrder = {
	"header", "range", "filter"
})
@XmlSeeAlso({
	SheetStructureDefaultT.class, SheetStructureT.class
})
public class StructureT {

	protected StructureHeaderT header;
	protected StructureRangeT range;
	protected StructureFilterT filter;
	@XmlAttribute(name = "id", required = true)
	protected String id;
	@XmlAttribute(name = "extends")
	protected String _extends;

	/**
	 * Gets the value of the header property.
	 *
	 * @return possible object is {@link StructureHeaderT }
	 *
	 */
	public StructureHeaderT getHeader() {
		return this.header;
	}

	/**
	 * Sets the value of the header property.
	 *
	 * @param value
	 *            allowed object is {@link StructureHeaderT }
	 *
	 */
	public void setHeader(StructureHeaderT value) {
		this.header = value;
	}

	/**
	 * Gets the value of the range property.
	 *
	 * @return possible object is {@link StructureRangeT }
	 *
	 */
	public StructureRangeT getRange() {
		return this.range;
	}

	/**
	 * Sets the value of the range property.
	 *
	 * @param value
	 *            allowed object is {@link StructureRangeT }
	 *
	 */
	public void setRange(StructureRangeT value) {
		this.range = value;
	}

	/**
	 * Gets the value of the filter property.
	 *
	 * @return possible object is {@link StructureFilterT }
	 *
	 */
	public StructureFilterT getFilter() {
		return this.filter;
	}

	/**
	 * Sets the value of the filter property.
	 *
	 * @param value
	 *            allowed object is {@link StructureFilterT }
	 *
	 */
	public void setFilter(StructureFilterT value) {
		this.filter = value;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the extends property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getExtends() {
		return this._extends;
	}

	/**
	 * Sets the value of the extends property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setExtends(String value) {
		this._extends = value;
	}

}
