/*******************************************************************************
 * #%L
 * Armedia Caliente
 * %%
 * Copyright (C) 2013 - 2019 Armedia, LLC
 * %%
 * This file is part of the Caliente software.
 *
 * If the software was purchased under a paid Caliente license, the terms of
 * the paid license agreement will prevail.  Otherwise, the software is
 * provided under the following open source license terms:
 *
 * Caliente is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Caliente is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Caliente. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.01 at 11:04:18 AM CST
//

package com.armedia.caliente.cli.flat2db.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for structureRange.t complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="structureRange.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="first" type="{http://www.armedia.com/ns/caliente/flat2db}naturalNumber.t" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="last" type="{http://www.armedia.com/ns/caliente/flat2db}naturalNumber.t"/>
 *           &lt;element name="count" type="{http://www.armedia.com/ns/caliente/flat2db}naturalNumber.t"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "structureRange.t", propOrder = {
	"first", "last", "count"
})
public class StructureRangeT {

	@XmlElement(name = "first-row")
	protected String first;
	@XmlElement(name = "last-row")
	protected String last;
	@XmlElement(name = "row-count")
	protected String count;

	/**
	 * Gets the value of the first property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFirst() {
		return this.first;
	}

	/**
	 * Sets the value of the first property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFirst(String value) {
		this.first = value;
	}

	/**
	 * Gets the value of the last property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLast() {
		return this.last;
	}

	/**
	 * Sets the value of the last property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLast(String value) {
		this.last = value;
	}

	/**
	 * Gets the value of the count property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCount() {
		return this.count;
	}

	/**
	 * Sets the value of the count property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setCount(String value) {
		this.count = value;
	}

}
