//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 11:04:18 AM CST 
//


package com.armedia.caliente.cli.flat2db.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataSource.t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataSource.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{http://www.armedia.com/ns/caliente/flat2db}properties.t"/>
 *         &lt;element name="startup" type="{http://www.armedia.com/ns/caliente/flat2db}sqlInitializerTasks.t" minOccurs="0"/>
 *         &lt;element name="on-insert" type="{http://www.armedia.com/ns/caliente/flat2db}sqlTasks.t" minOccurs="0"/>
 *         &lt;element name="on-error" type="{http://www.armedia.com/ns/caliente/flat2db}sqlTasks.t" minOccurs="0"/>
 *         &lt;element name="shutdown" type="{http://www.armedia.com/ns/caliente/flat2db}sqlInitializerTasks.t" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.armedia.com/ns/caliente/flat2db}id_string.t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataSource.t", propOrder = {
    "properties",
    "startup",
    "onInsert",
    "onError",
    "shutdown"
})
public class DataSourceT {

    @XmlElement(required = true)
    protected PropertiesT properties;
    protected SqlInitializerTasksT startup;
    @XmlElement(name = "on-insert")
    protected SqlTasksT onInsert;
    @XmlElement(name = "on-error")
    protected SqlTasksT onError;
    protected SqlInitializerTasksT shutdown;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesT }
     *     
     */
    public PropertiesT getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesT }
     *     
     */
    public void setProperties(PropertiesT value) {
        this.properties = value;
    }

    /**
     * Gets the value of the startup property.
     * 
     * @return
     *     possible object is
     *     {@link SqlInitializerTasksT }
     *     
     */
    public SqlInitializerTasksT getStartup() {
        return startup;
    }

    /**
     * Sets the value of the startup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlInitializerTasksT }
     *     
     */
    public void setStartup(SqlInitializerTasksT value) {
        this.startup = value;
    }

    /**
     * Gets the value of the onInsert property.
     * 
     * @return
     *     possible object is
     *     {@link SqlTasksT }
     *     
     */
    public SqlTasksT getOnInsert() {
        return onInsert;
    }

    /**
     * Sets the value of the onInsert property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlTasksT }
     *     
     */
    public void setOnInsert(SqlTasksT value) {
        this.onInsert = value;
    }

    /**
     * Gets the value of the onError property.
     * 
     * @return
     *     possible object is
     *     {@link SqlTasksT }
     *     
     */
    public SqlTasksT getOnError() {
        return onError;
    }

    /**
     * Sets the value of the onError property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlTasksT }
     *     
     */
    public void setOnError(SqlTasksT value) {
        this.onError = value;
    }

    /**
     * Gets the value of the shutdown property.
     * 
     * @return
     *     possible object is
     *     {@link SqlInitializerTasksT }
     *     
     */
    public SqlInitializerTasksT getShutdown() {
        return shutdown;
    }

    /**
     * Sets the value of the shutdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlInitializerTasksT }
     *     
     */
    public void setShutdown(SqlInitializerTasksT value) {
        this.shutdown = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
