//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 11:04:18 AM CST 
//


package com.armedia.caliente.cli.flat2db.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rollbackChangesetBy.t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rollbackChangesetBy.t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="tag"/>
 *     &lt;enumeration value="number"/>
 *     &lt;enumeration value="date"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rollbackChangesetBy.t")
@XmlEnum
public enum RollbackChangesetByT {

    @XmlEnumValue("tag")
    TAG("tag"),
    @XmlEnumValue("number")
    NUMBER("number"),
    @XmlEnumValue("date")
    DATE("date");
    private final String value;

    RollbackChangesetByT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RollbackChangesetByT fromValue(String v) {
        for (RollbackChangesetByT c: RollbackChangesetByT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
