//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 11:04:18 AM CST 
//


package com.armedia.caliente.cli.flat2db.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sqlInitializerTasks.t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sqlInitializerTasks.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;group ref="{http://www.armedia.com/ns/caliente/flat2db}sqlTasks"/>
 *           &lt;group ref="{http://www.armedia.com/ns/caliente/flat2db}sqlInitializerTasks"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sqlInitializerTasks.t", propOrder = {
    "sqlOrSqlScriptOrChangeset"
})
public class SqlInitializerTasksT {

    @XmlElementRefs({
        @XmlElementRef(name = "rollback-changeset", namespace = "http://www.armedia.com/ns/caliente/flat2db", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "changeset", namespace = "http://www.armedia.com/ns/caliente/flat2db", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sql", namespace = "http://www.armedia.com/ns/caliente/flat2db", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sql-script", namespace = "http://www.armedia.com/ns/caliente/flat2db", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> sqlOrSqlScriptOrChangeset;

    /**
     * Gets the value of the sqlOrSqlScriptOrChangeset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sqlOrSqlScriptOrChangeset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSqlOrSqlScriptOrChangeset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link RollbackChangesetT }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getSqlOrSqlScriptOrChangeset() {
        if (sqlOrSqlScriptOrChangeset == null) {
            sqlOrSqlScriptOrChangeset = new ArrayList<JAXBElement<?>>();
        }
        return this.sqlOrSqlScriptOrChangeset;
    }

}
