//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.09 at 11:48:15 AM CST
//

package com.armedia.caliente.store.local.xml;

import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.armedia.caliente.store.CmfValueType;
import com.armedia.caliente.store.local.XmlProperty;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "property.t", namespace = ObjectFactory.NAMESPACE, propOrder = {
	"value"
})
public class PropertyT extends XmlProperty {

	protected void beforeMarshal(Marshaller m) {
		this.type = this.dataType.name();
	}

	protected void afterUnmarshal(Unmarshaller u, Object parent) {
		this.dataType = CmfValueType.valueOf(this.type);
	}
}