//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.08.15 at 05:58:25 PM CST
//

package com.delta.cmsmf.io.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.delta.cmsmf.io.AttributeType;

/**
 * <p>
 * Java class for attribute.t complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="attribute.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://www.armedia.com/ns/cmsmf/object}value.t" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.armedia.com/ns/cmsmf/object}non_empty_string.t" />
 *       &lt;attribute name="repeating" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type" use="required" type="{http://www.armedia.com/ns/cmsmf/object}non_empty_string.t" />
 *       &lt;attribute name="maxLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attribute.t", propOrder = {
	"value"
})
public class AttributeT {

	@XmlElement(required = true)
	@XmlElementWrapper(name = "value")
	protected List<String> value;

	@XmlAttribute(required = true)
	protected String name;

	@XmlAttribute(required = true)
	protected boolean repeating;

	@XmlAttribute(required = true)
	protected AttributeType type;

	@XmlAttribute
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger maxLength;

	@XmlAttribute(required = true)
	protected String id;

	/**
	 * Gets the value of the value property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the value property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ValueT }
	 * 
	 * 
	 */
	public List<String> getValue() {
		if (this.value == null) {
			this.value = new ArrayList<String>();
		}
		return this.value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		if (value == null) { throw new IllegalArgumentException("Must provide a valid name"); }
		if (value.matches("^.*\\s.*$")) { throw new IllegalArgumentException(String.format(
			"Illegal attribute name [%s]", value)); }
		this.name = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		if (value == null) { throw new IllegalArgumentException("Must provide a valid id"); }
		this.id = value;
	}

	/**
	 * Gets the value of the repeating property.
	 * 
	 */
	public boolean isRepeating() {
		return this.repeating;
	}

	/**
	 * Sets the value of the repeating property.
	 * 
	 */
	public void setRepeating(boolean value) {
		this.repeating = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public AttributeType getType() {
		return this.type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(AttributeType value) {
		if (value == null) { throw new IllegalArgumentException("Must provide a valid AttributeType"); }
		this.type = value;
	}

	/**
	 * Gets the value of the maxLength property.
	 * 
	 * @return
	 *         possible object is {@link BigInteger }
	 * 
	 */
	public int getMaxLength() {
		if (this.maxLength == null) { return 0; }
		return this.maxLength.intValue();
	}

	/**
	 * Sets the value of the maxLength property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxLength(int value) {
		if (value <= 0) {
			value = 0;
		}
		this.maxLength = BigInteger.valueOf(value);
	}

}
