//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.08.15 at 05:58:25 PM CST
//

package com.delta.cmsmf.io.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.apache.commons.codec.DecoderException;
import org.apache.commons.codec.binary.Hex;

/**
 * <p>
 * Java class for object.t complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="object.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribute" type="{http://www.armedia.com/ns/cmsmf/object}attribute.t" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.armedia.com/ns/cmsmf/object}id_string.t" />
 *       &lt;attribute name="type" use="required" type="{http://www.armedia.com/ns/cmsmf/object}non_empty_string.t" />
 *       &lt;attribute name="filestore" type="{http://www.armedia.com/ns/cmsmf/object}non_empty_string.t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "object.t", propOrder = {
	"attribute"
})
public class ObjectT {

	@XmlElement(required = true)
	protected List<AttributeT> attribute;

	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(HexBinaryAdapter.class)
	protected byte[] id;

	@XmlAttribute(required = true)
	protected String type;

	@XmlAttribute
	protected String filestore;

	/**
	 * Gets the value of the attribute property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the attribute property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAttribute().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link AttributeT }
	 * 
	 * 
	 */
	public List<AttributeT> getAttribute() {
		if (this.attribute == null) {
			this.attribute = new ArrayList<AttributeT>();
		}
		return this.attribute;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getId() {
		return new String(Hex.encodeHex(this.id));
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) throws DecoderException {
		// Decode to binary
		this.id = Hex.decodeHex(value.toCharArray());
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the filestore property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getFilestore() {
		return this.filestore;
	}

	/**
	 * Sets the value of the filestore property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFilestore(String value) {
		this.filestore = value;
	}

}
