#!/bin/bash
#*******************************************************************************
# #%L
# Armedia Caliente
# %%
# Copyright (C) 2013 - 2019 Armedia, LLC
# %%
# This file is part of the Caliente software.
#
# If the software was purchased under a paid Caliente license, the terms of
# the paid license agreement will prevail.  Otherwise, the software is
# provided under the following open source license terms:
#
# Caliente is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Caliente is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Caliente. If not, see <http://www.gnu.org/licenses/>.
# #L%
#*******************************************************************************
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE="[-c] -h alfrescoUrl [-u user -p password | -A authenticationFile]"

ALF_URL=""
ALF_USER=""
ALF_PASS=""
ALF_PASS_SET="false"
PREFER_CURL="false"

while getopts ":ch:u:p:A:" OPT "${@}" ; do
	case "${OPT}" in
		c )	${PREFER_CURL} && fail "May not specify -c more than once"
			PREFER_CURL="true"
			;;
		h )	[ -n "${ALF_URL}" ] && fail "May not specify more than one -h value"
			[ -z "${OPTARG}" ] && fail "May not specify an empty URL"
			ALF_URL="${OPTARG}"
			;;
		u )	[ -n "${ALF_USER}" ] && fail "May not specify more than one -u value"
			[ -n "${ALF_AUTH}" ] && fail "May not specify -A and -u"
			[ -z "${OPTARG}" ] && fail "May not specify an empty username"
			ALF_USER="${OPTARG}"
			;;
		p )	${ALF_PASS_SET} && fail "May not specify more than one -p value"
			[ -n "${ALF_AUTH}" ] && fail "May not specify -A and -p"
			ALF_PASS="${OPTARG}"
			ALF_PASS_SET="true"
			;;
		A )	[ -n "${ALF_USER}" ] && fail "May not specify -u and -A"
			${ALF_PASS_SET} && fail "May not specify -p and -A"
			[ -z "${OPTARG}" ] && fail "May not specify an empty authentication file"
			ALF_AUTH="${OPTARG}"
			[ -e "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] does not exist"
			[ -f "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] is not a regular file"
			[ -r "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] can't be read"
			;;
		? )	OI="$(( OPTIND - 1 ))"
			usage "Parameter ${!OI} is not valid or unexpected here"
			;;
	esac
done

[ -z "${ALF_URL}" ] && usage "-h requires a non-empty value"
[ -z "${ALF_USER}" -a -z "${ALF_AUTH}" ] && usage "Must provide either -u or -A"
[ -n "${ALF_USER}" ] && ! ${ALF_PASS_SET} && usage "Must provide a password using -p, or use -A"

JQ="$(find_exe jq true)"
WGET="$(find_exe wget)"
CURL="$(find_exe curl)"
[ -z "${WGET}" -a -z "${CURL}" ] && fail "Must have either curl or wget installed - can't continue"

if [ -n "${ALF_AUTH}" ] ; then
	AUTH_DATA="$(cat "${ALF_AUTH}")"
	parse "." <<< "${AUTH_DATA}" &>/dev/null || fail "The authentication file [${ALF_AUTH}] must have proper JSON syntax"
	ALF_USER="$(parse_value ".user" <<< "${AUTH_DATA}")"
	ALF_PASS="$(parse_value ".password" <<< "${AUTH_DATA}")"
	ALF_PASS_SET="true"
fi

# Choose which getter function to use. WGET will be preferred
[ -n "${CURL}" ] && CALL="curl_call"
[ -n "${WGET}" ] && CALL="wget_call"
${PREFER_CURL} && [ -n "${CURL}" ] && CALL="curl_call"

FULL_STATUS_JSON="$(call_alfresco GET "${ALF_URL}/s/bulk/import/status.json")"
[ ${?} -ne 0 ] && fail "Failed to retrieve the status data"

STATUS="$(parse_value ".processingState" <<< "${FULL_STATUS_JSON}")"
SOURCE="$(parse_value ".targetPath" <<< "${FULL_STATUS_JSON}")"
TARGET="$(parse_value ".sourceParameters[\"Source Directory\"]" <<< "${FULL_STATUS_JSON}")"
DRYRUN="$(parse_value ".dryRun" <<< "${FULL_STATUS_JSON}")"
ERROR_INFO="$(parse ".errorInfo" <<< "${FULL_STATUS_JSON}")"
ERRORS="$(parse ". | length" <<< "${ERROR_INFO}")"

case "${STATUS^^}" in
	"SCANNING"	| \
	"IMPORTING"	| \
	"STOPPING"	| \
	"PAUSED"	)
		say "BI is currently ${STATUS}, with ${ERRORS} errors reported"
		say "\tSOURCE : [${SOURCE}]"
		say "\tTARGET : [${TARGET}]"
		say "\tDRY RUN: ${DRYRUN}"
		;;

	"STOPPED"	)
		say "BI was stopped with ${ERRORS} errors reported"
		say "\tSOURCE : [${SOURCE}]"
		say "\tTARGET : [${TARGET}]"
		say "\tDRY RUN: ${DRYRUN}"
		;;

	"NEVER RUN"	)
		say "BI hasn't been run yet"
		exit 0
		;;

	"SUCCEEDED" )
		say "BI was successful with ${ERRORS} errors reported"
		say "\tSOURCE : [${SOURCE}]"
		say "\tTARGET : [${TARGET}]"
		say "\tDRY RUN: ${DRYRUN}"
		exit 0
		;;

	"FAILED"	)
		say "BI was run but failed with ${ERRORS} errors reported"
		say "\tSOURCE : [${SOURCE}]"
		say "\tTARGET : [${TARGET}]"
		say "\tDRY RUN: [${DRYRUN}]"
		;;

	* )
		say "Unknown BI status [${STATUS}]"
		exit 2
		;;
esac

for (( i = 0 ; i < ${ERRORS} ; i++ )) ; do
	ERR="$(parse ".[${i}]" <<< "${ERROR_INFO}")"
	TIMESTAMP="$(parse_value ".TimeStamp" <<< "${ERR}")"
	ITEM="$(parse_value ".Item" <<< "${ERR}")"
	DIRECTORY="$(parse_value ".Directory" <<< "${ERR}")"
	SOURCE="$(parse_value ".Source" <<< "${ERR}")"
	ERROR="$(parse_value ".Error" <<< "${ERR}")"
	[ ${i} -eq 0 ] && say "============================================================"
	if ${SOURCE} ; then
		# An error from the source, no item info
		say "Source engine error:"
	else
		TYPE="Document"
		${DIRECTORY} && TYPE="Folder"
		say "${TYPE} import error:"
	fi
	say "${ERROR}"
	say "============================================================"
done
