package com.armedia.cmf.engine.sharepoint;

public enum ShptAttributes {

	//
	OBJECT_ID,
	OBJECT_CLASS,
	OBJECT_TYPE,
	OBJECT_ISSUER,
	OBJECT_NAME,
	SITE_ADMIN,
	PRINCIPAL_TYPE,
	PRINCIPAL_ID,
	PRINCIPAL_ID_ISSUER,
	EMAIL,
	TITLE,
	USER_GROUPS,
	USER_ROLES,
	AUTO_ACCEPT_MEMBERSHIP_REQUEST,
	ALLOW_MEMBERSHIP_REQUEST,
	ALLOW_MEMBERS_EDIT_MEMBERSHIP,
	GROUP_MEMBERS,
	OWNER_TITLE,
	GROUP_OWNER,
	DESCRIPTION,
	CONTENT_TYPE,
	CONTENT_SIZE,
	CONTENT_HASH,
	OWNER,
	OWNER_PERMISSION,
	GROUP,
	GROUP_PERMISSION,
	CREATOR,
	CREATE_DATE,
	MODIFIER,
	MODIFICATION_DATE,
	ACCESSOR,
	ACCESS_DATE,
	PARENTS,
	PATHS,
	LOGIN_NAME,
	LOGIN_DOMAIN,
	HOME_FOLDER,
	WELCOME_PAGE,
	VERSION,
	//
	;

	public final String name;

	private ShptAttributes() {
		this.name = name().toLowerCase();
	}
}