#!/bin/bash

find_caliente_exe() {
	local EXE="$(find . -maxdepth 1 -type f -name 'caliente-*-exe.jar' | sort | tail -1)"
	[ -n "${EXE}" ] && { echo "${EXE}" ; return 0 ; }
	EXE="$(find . -mindepth 2 -maxdepth 2 -type f -name 'caliente-*-exe.jar' | sort | tail -1)"
	[ -n "${EXE}" ] && { echo "${EXE}" ; return 0 ; }
	return 1
}

EXE="$(find_caliente_exe)"
[ -z "${EXE}" ] && { echo "ERROR: No Caliente executable JAR was found" ; exit 1 ; }

DEBUG_FLAGS=()
case "${1,,}" in
	--debug | -d )
		DEBUG_FLAGS=("-Xdebug" "-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=0.0.0.0:9999")
		shift
		set -x
		;;
	* ) ;;
esac

echo -e "Launching from [${EXE}]..."
exec java \
	-Xms4g -Xmx8g \
	"${DEBUG_FLAGS[@]}" \
	-jar "${EXE}" "${@}"
