//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.09 at 11:48:15 AM CST
//

package com.armedia.cmf.storage.local.xml;

import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import com.armedia.cmf.storage.StoredDataType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "property.t", propOrder = {
	"value"
})
public class PropertyT {

	@XmlValue
	protected String value;

	@XmlAttribute(required = true)
	protected String name;

	@XmlAttribute(required = true)
	protected String type;

	@XmlTransient
	private StoredDataType dataType;

	protected void beforeMarshal(Marshaller m) {
		this.type = this.dataType.name();
	}

	protected void afterUnmarshal(Unmarshaller u, Object parent) {
		this.dataType = StoredDataType.valueOf(this.type);
	}

	/**
	 * Gets the value of the value property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getValue() {
		return this.value;
	}

	/**
	 * Sets the value of the value property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link StoredDataType }
	 *
	 */
	public StoredDataType getType() {
		return this.dataType;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *            allowed object is {@link StoredDataType }
	 *
	 */
	public void setType(StoredDataType value) {
		this.dataType = value;
	}

}
