//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.09 at 11:48:15 AM CST
//

package com.armedia.caliente.store.local.xml.legacy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.armedia.caliente.store.local.XmlProperty;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "property.t", propOrder = {
	"value"
})
public class PropertyT extends XmlProperty {
}