//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.09 at 11:48:15 AM CST
//

package com.armedia.caliente.store.local.xml.legacy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.armedia.caliente.store.local.XmlStoreProperties;

@XmlRootElement(name = "store-properties")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "storeProperties.t", namespace = ObjectFactory.NAMESPACE, propOrder = {
	"property"
})
public class StorePropertiesT implements XmlStoreProperties<PropertyT> {

	@XmlElement(name = "property", required = false)
	protected List<PropertyT> property;

	@Override
	public List<PropertyT> getProperty() {
		if (this.property == null) {
			this.property = new ArrayList<>();
		}
		return this.property;
	}
}