//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.09 at 11:48:15 AM CST
//

package com.armedia.cmf.storage.local.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.armedia.cmf.storage.local.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	public static final String NAMESPACE = "http://www.armedia.com/ns/cmf/stores/local/store-properties";

	private final static QName _StoreProperties_QNAME = new QName(ObjectFactory.NAMESPACE, "store-properties");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes
	 * for package: com.armedia.cmf.storage.local.xml
	 *
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link StorePropertiesT }
	 *
	 */
	public StorePropertiesT createStorePropertiesT() {
		return new StorePropertiesT();
	}

	/**
	 * Create an instance of {@link PropertyT }
	 *
	 */
	public PropertyT createPropertyT() {
		return new PropertyT();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link StorePropertiesT }{@code >}
	 *
	 */
	@XmlElementDecl(namespace = ObjectFactory.NAMESPACE, name = "store-properties")
	public JAXBElement<StorePropertiesT> createStoreProperties(StorePropertiesT value) {
		return new JAXBElement<StorePropertiesT>(ObjectFactory._StoreProperties_QNAME, StorePropertiesT.class, null,
			value);
	}

}
