#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${0}")"
SCRIPT="$(basename "${0}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE_DETAILS="[-c] -h alfrescoUrl [-u user -p password | -A authenticationFile] -s source -t target"

start_export() {
	local SRC="$(urlencode "${1}")"
	local TGT="$(urlencode "${2}")"
	call_alfresco "${ALF_URL}/s/bulk/export/initiate?sourceLocation=${SRC}&exportLocation=${TGT}&mode=CALIENTE" POST
}

ALF_URL=""
ALF_USER=""
ALF_PASS=""
ALF_PASS_SET="false"
PREFER_CURL="false"
DRYRUN="false"
REPLACE="false"

while getopts ":ch:u:p:A:s:t:" OPT "${@}" ; do
	case "${OPT}" in
		c )	${PREFER_CURL} && fail "May not specify -c more than once"
			PREFER_CURL="true"
			;;
		h )	[ -n "${ALF_URL}" ] && fail "May not specify more than one -h value"
			[ -z "${OPTARG}" ] && fail "May not specify an empty URL"
			ALF_URL="${OPTARG}"
			;;
		u )	[ -n "${ALF_USER}" ] && fail "May not specify more than one -u value"
			[ -n "${ALF_AUTH}" ] && fail "May not specify -A and -u"
			[ -z "${OPTARG}" ] && fail "May not specify an empty username"
			ALF_USER="${OPTARG}"
			;;
		p )	${ALF_PASS_SET} && fail "May not specify more than one -p value"
			[ -n "${ALF_AUTH}" ] && fail "May not specify -A and -p"
			ALF_PASS="${OPTARG}"
			ALF_PASS_SET="true"
			;;
		A )	[ -n "${ALF_USER}" ] && fail "May not specify -u and -A"
			${ALF_PASS_SET} && fail "May not specify -p and -A"
			[ -z "${OPTARG}" ] && fail "May not specify an empty authentication file"
			ALF_AUTH="${OPTARG}"
			[ -e "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] does not exist"
			[ -f "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] is not a regular file"
			[ -r "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] can't be read"
			;;
		s )	[ -n "${SOURCE}" ] && fail "May not specify -s more than once"
			[ -z "${OPTARG}" ] && fail "May not specify an empty source path"
			SOURCE="$(normalize_path "${OPTARG}")"
			[ ${?} -ne 0 ] && fail "Illegal source path [${OPTARG}] - not fully normalized"
			;;
		t )	[ -n "${TARGET}" ] && fail "May not specify -t more than once"
			[ -z "${OPTARG}" ] && fail "May not specify an empty target path"
			TARGET="$(normalize_path "${OPTARG}")"
			[ ${?} -ne 0 ] && fail "Illegal target path [${OPTARG}] - not fully normalized"
			;;
		? )	OI="$(( OPTIND - 1 ))"
			usage "Parameter ${!OI} is not valid or unexpected here"
			;;
	esac
done

[ -z "${SOURCE}" ] && usage "-s requires a non-empty value"
[ -z "${TARGET}" ] && usage "-t requires a non-empty value"
[ -z "${ALF_URL}" ] && usage "-h requires a non-empty value"
[ -z "${ALF_USER}" -a -z "${ALF_AUTH}" ] && usage "Must provide either -u or -A"
[ -n "${ALF_USER}" ] && ! ${ALF_PASS_SET} && usage "Must provide a password using -p, or use -A"

JQ="$(find_exe jq true)"
WGET="$(find_exe wget)"
CURL="$(find_exe curl)"
[ -z "${WGET}" -a -z "${CURL}" ] && fail "Must have either curl or wget installed - can't continue"

if [ -n "${ALF_AUTH}" ] ; then
	AUTH_DATA="$(cat "${ALF_AUTH}")"
	parse "." <<< "${AUTH_DATA}" &>/dev/null || fail "The authentication file [${ALF_AUTH}] must have proper JSON syntax"
	ALF_USER="$(parse_value ".user" <<< "${AUTH_DATA}")"
	ALF_PASS="$(parse_value ".password" <<< "${AUTH_DATA}")"
	ALF_PASS_SET="true"
fi

# Choose which getter function to use. WGET will be preferred
[ -n "${CURL}" ] && CALL="curl_call"
[ -n "${WGET}" ] && CALL="wget_call"
${PREFER_CURL} && [ -n "${CURL}" ] && CALL="curl_call"

FULL_STATUS_JSON="$(call_alfresco "${ALF_URL}/s/bulk/export/status.json")"
[ ${?} -ne 0 ] && fail "Failed to retrieve the status data"

STATUS="$(parse_value ".processingState" <<< "${FULL_STATUS_JSON}")"
case "${STATUS^^}" in
	"NEVER RUN"		| \
	"SUCCEEDED"		| \
	"FAILED"		| \
	"STOPPED"		) ;;

	"PROCESSING"	| \
	"STOPPING"		| \
	"PAUSED"		)
		SOURCE="$(parse_value ".sourceName" <<< "${FULL_STATUS_JSON}")"
		TARGET="$(parse_value ".targetPath" <<< "${FULL_STATUS_JSON}")"
		err "ERROR: BE is active (${STATUS^^})"
		err "\tSOURCE : [${SOURCE}]"
		err "\tTARGET : [${TARGET}]"
		exit 1
		;;

	* )
		# Unknown!!
		say "Unknown BE status [${STATUS}]"
		exit 2
		;;
esac

say "$(date): Launching BE at [${ALF_URL}] as [${ALF_USER}]..."
say "\tSOURCE : [${SOURCE}]"
say "\tTARGET : [${TARGET}]"
OUT="$(start_export "${SOURCE}" "${TARGET}")"
RC="${?}"
if [ ${RC} -eq 0 ] ; then
	say "$(date): Bulk Export started"
else
	say "$(date): Bulk Export was not started (RC=${RC})"
	say "${OUT}"
fi
exit ${RC}
