#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${0}")"
SCRIPT="$(basename "${0}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

for log in "${@}" ; do
	egrep "^[[:space:]]export.predicate[[:space:]]=[[:space:]]\[.*\]$" "${log}"
done | sed -e 's/^\sexport.predicate\s=\s\[//g' -e 's/\]$//g' -e 's/^\([^[:space:]]\+\)/\1 (ALL)/g'
