#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${0}")"
SCRIPT="$(basename "${0}")"

say() {
	echo -e "${@}"
}

err() {
	say "${@}" 1>&2
}

fail() {
	err "ERROR: ${@}"
	exit 1
}

for log in "${@}" ; do
	egrep "^[[:space:]]export.predicate[[:space:]]=[[:space:]]\[.*\]$" "${log}"
done | sed -e 's/^\sexport.predicate\s=\s\[//g' -e 's/\]$//g' -e 's/^\([^[:space:]]\+\)/\1 (ALL)/g'
