#!/bin/bash
#*******************************************************************************
# #%L
# Armedia Caliente
# %%
# Copyright (C) 2013 - 2019 Armedia, LLC
# %%
# This file is part of the Caliente software.
#
# If the software was purchased under a paid Caliente license, the terms of
# the paid license agreement will prevail.  Otherwise, the software is
# provided under the following open source license terms:
#
# Caliente is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Caliente is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Caliente. If not, see <http://www.gnu.org/licenses/>.
# #L%
#*******************************************************************************
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE="basetype"

[ ${#} -ne 1 ] && usage "Must provide the base type to generate the prediate with"
BASETYPE="${1}"
[ -z "${BASETYPE}" ] && usage "The base type may not be an empty string"
[[ "${BASETYPE}" =~ ^.*[^a-zA-Z0-9_].*$ ]] && usage "The base type must be a valid documentum type name (${BASETYPE})"

say "${BASETYPE} where r_object_id in ("
COMMA=" "
while read r_object_id rest ; do
	say "${COMMA} '${r_object_id}'"
	COMMA=","
done
say ")"
