#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${0}")"
SCRIPT="$(basename "${0}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE_DETAILS="basetype"

[ ${#} -ne 1 ] && usage "Must provide the base type to generate the prediate with"
BASETYPE="${1}"
[ -z "${BASETYPE}" ] && usage "The base type may not be an empty string"
[[ "${BASETYPE}" =~ ^.*[^a-zA-Z0-9_].*$ ]] && usage "The base type must be a valid documentum type name (${BASETYPE})"

say "${BASETYPE} where r_object_id in ("
COMMA=" "
while read r_object_id rest ; do
	say "${COMMA} '${r_object_id}'"
	COMMA=","
done
say ")"
