#!/bin/bash
#*******************************************************************************
# #%L
# Armedia Caliente
# %%
# Copyright (C) 2013 - 2019 Armedia, LLC
# %%
# This file is part of the Caliente software.
#
# If the software was purchased under a paid Caliente license, the terms of
# the paid license agreement will prevail.  Otherwise, the software is
# provided under the following open source license terms:
#
# Caliente is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Caliente is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Caliente. If not, see <http://www.gnu.org/licenses/>.
# #L%
#*******************************************************************************
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE="[-c] -h alfrescoUrl [-u user -p password | -A authenticationFile] -s source [-i indexName]"

start_pp() {
	local SRC="${1}"
	local IDX="${2}"
	SRC="$(sed -e 's;^/\+;;g' <<< "${SRC}")"
	SRC="${SRC}${SRC:+/}${IDX}"
	call_alfresco POST "${ALF_URL}/s/caliente/migration/initiate" "robjectid=${SRC}"
}

ALF_URL=""
ALF_USER=""
ALF_PASS=""
ALF_PASS_SET="false"
PREFER_CURL="false"
DRYRUN="false"
REPLACE="false"

while getopts ":ch:u:p:A:s:i:" OPT "${@}" ; do
	case "${OPT}" in
		c )	${PREFER_CURL} && fail "May not specify -c more than once"
			PREFER_CURL="true"
			;;
		h )	[ -n "${ALF_URL}" ] && fail "May not specify more than one -h value"
			[ -z "${OPTARG}" ] && fail "May not specify an empty URL"
			ALF_URL="${OPTARG}"
			;;
		u )	[ -n "${ALF_USER}" ] && fail "May not specify more than one -u value"
			[ -n "${ALF_AUTH}" ] && fail "May not specify -A and -u"
			[ -z "${OPTARG}" ] && fail "May not specify an empty username"
			ALF_USER="${OPTARG}"
			;;
		p )	${ALF_PASS_SET} && fail "May not specify more than one -p value"
			[ -n "${ALF_AUTH}" ] && fail "May not specify -A and -p"
			ALF_PASS="${OPTARG}"
			ALF_PASS_SET="true"
			;;
		A )	[ -n "${ALF_USER}" ] && fail "May not specify -u and -A"
			${ALF_PASS_SET} && fail "May not specify -p and -A"
			[ -z "${OPTARG}" ] && fail "May not specify an empty authentication file"
			ALF_AUTH="${OPTARG}"
			[ -e "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] does not exist"
			[ -f "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] is not a regular file"
			[ -r "${ALF_AUTH}" ] || fail "The authentication file [${ALF_AUTH}] can't be read"
			;;
		s )	[ -n "${SOURCE}" ] && fail "May not specify -s more than once"
			[ -z "${OPTARG}" ] && fail "May not specify an empty source path"
			SOURCE="$(normalize_path "${OPTARG}")"
			[ ${?} -ne 0 ] && fail "Illegal source path [${OPTARG}] - not fully normalized"
			;;
		i )	[ -n "${INDEX_NAME}" ] && fail "May not specify -i more than once"
			[ -z "${OPTARG}" ] && fail "May not specify an empty index name"
			INDEX_NAME="$(normalize_path "${OPTARG}")"
			[ ${?} -ne 0 ] && fail "Illegal index name [${OPTARG}] - not fully normalized"
			;;
		? )	OI="$(( OPTIND - 1 ))"
			usage "Parameter ${!OI} is not valid or unexpected here"
			;;
	esac
done

[ -z "${INDEX_NAME}" ] && INDEX_NAME="CALIENTE_INGESTION_INDEX.txt"
INDEX_NAME="$(sed -e 's;^/\+;;g' <<< "${INDEX_NAME}")"

[ -z "${SOURCE}" ] && usage "-s requires a non-empty value"
[ -z "${ALF_URL}" ] && usage "-h requires a non-empty value"
[ -z "${ALF_USER}" -a -z "${ALF_AUTH}" ] && usage "Must provide either -u or -A"
[ -n "${ALF_USER}" ] && ! ${ALF_PASS_SET} && usage "Must provide a password using -p, or use -A"

JQ="$(find_exe jq true)"
WGET="$(find_exe wget)"
CURL="$(find_exe curl)"
[ -z "${WGET}" -a -z "${CURL}" ] && fail "Must have either curl or wget installed - can't continue"

if [ -n "${ALF_AUTH}" ] ; then
	AUTH_DATA="$(cat "${ALF_AUTH}")"
	parse "." <<< "${AUTH_DATA}" &>/dev/null || fail "The authentication file [${ALF_AUTH}] must have proper JSON syntax"
	ALF_USER="$(parse_value ".user" <<< "${AUTH_DATA}")"
	ALF_PASS="$(parse_value ".password" <<< "${AUTH_DATA}")"
	ALF_PASS_SET="true"
fi

# Choose which getter function to use. WGET will be preferred
[ -n "${CURL}" ] && CALL="curl_call"
[ -n "${WGET}" ] && CALL="wget_call"
${PREFER_CURL} && [ -n "${CURL}" ] && CALL="curl_call"

FULL_STATUS_JSON="$(call_alfresco GET "${ALF_URL}/s/caliente/migration/status.json")"
[ ${?} -ne 0 ] && fail "Failed to retrieve the status data"

STATUS="$(parse_value ".processingState" <<< "${FULL_STATUS_JSON}")"
case "${STATUS^^}" in
	"NULL"		| \
	"NEVER RUN"	| \
	"SUCCEEDED"	| \
	"FAILED"	| \
	"STOPPED"	) ;;

	"PROCESSING"	| \
	"STOPPING"		| \
	"PAUSED"		)
		SOURCE="$(parse_value ".sourceName" <<< "${FULL_STATUS_JSON}")"
		DRYRUN="$(parse_value ".dryRun" <<< "${FULL_STATUS_JSON}")"
		ERRORS="$(parse_value ".errorInfo | length" <<< "${FULL_STATUS_JSON}")"
		err "ERROR: PP is active (${STATUS^^})"
		err "\tSOURCE : [${SOURCE}]"
		exit 1
		;;

	* )
		# Unknown!!
		say "Unknown PP status [${STATUS}]"
		exit 2
		;;
esac

# Remove leading slashes
SOURCE="$(sed -e 's;^/\+;;g' <<< "${SOURCE}")"
say "Launching PP at [${ALF_URL}] as [${ALF_USER}]..."
say "\tSOURCE : [${SOURCE}]"
say "\tINDEX  : [${INDEX_NAME}]"
start_pp "${SOURCE}" "${INDEX_NAME}"
RC="${?}"
if [ ${RC} -eq 0 ] ; then
	say "Post-Processor started"
else
	say "Post-Processor was not started (RC=${RC})"
fi
exit ${RC}
