#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE="manifest1 [manifest2 manifest3 ... manifestN]"

do_list() {
	local manifest="${1}"
	[ -e "${manifest}" ] || { err "ERROR: manifest [${manifest}] does not exist" ; return 1 ; }
	[ -f "${manifest}" ] || { err "ERROR: manifest [${manifest}] is not a regular file" ; return 1 ; }
	"${CSVTOOL}" -u ' ' col 3,5,7 "${manifest}" | grep -v "^TYPE "
}

[ ${#} -lt 1 ] && usage "Must provide at least one manifest name"

CSVTOOL=""
for n in "${@}" ; do
	[ -z "${CSVTOOL}" ] && CSVTOOL="$(find_exe csvtool true)"
	do_list "${n}"
done
