#!/bin/bash
#*******************************************************************************
# #%L
# Armedia Caliente
# %%
# Copyright (C) 2013 - 2019 Armedia, LLC
# %%
# This file is part of the Caliente software.
#
# If the software was purchased under a paid Caliente license, the terms of
# the paid license agreement will prevail.  Otherwise, the software is
# provided under the following open source license terms:
#
# Caliente is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Caliente is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Caliente. If not, see <http://www.gnu.org/licenses/>.
# #L%
#*******************************************************************************
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

if ! . "${BASEDIR}/caliente.lib.sh" ; then
	echo "Failed to load the main script library"
	exit 99
fi

USAGE="manifest1 [manifest2 manifest3 ... manifestN]"

do_list() {
	local manifest="${1}"
	[ -e "${manifest}" ] || { err "ERROR: manifest [${manifest}] does not exist" ; return 1 ; }
	[ -f "${manifest}" ] || { err "ERROR: manifest [${manifest}] is not a regular file" ; return 1 ; }
	"${CSVTOOL}" -u ' ' col 3,5,7 "${manifest}" | grep -v "^TYPE "
}

[ ${#} -lt 1 ] && usage "Must provide at least one manifest name"

CSVTOOL=""
for n in "${@}" ; do
	[ -z "${CSVTOOL}" ] && CSVTOOL="$(find_exe csvtool true)"
	do_list "${n}"
done
