#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${0}")"
SCRIPT="$(basename "${0}")"

say() {
	echo -e "${@}"
}

err() {
	say "${@}" 1>&2
}

fail() {
	err "ERROR: ${@}"
	exit 1
}

do_list() {
	local manifest="${1}"
	[ -e "${manifest}" ] || { err "ERROR: manifest [${manifest}] does not exist" ; return 1 ; }
	[ -f "${manifest}" ] || { err "ERROR: manifest [${manifest}] is not a regular file" ; return 1 ; }
	"${CSVTOOL}" -u ' ' col 3,5,7 "${manifest}" | grep -v "^TYPE "
}

CSVTOOL="$(which csvtool)"
[ -z "${CSVTOOL}" ] && CSVTOOL="/usr/bin/csvtool"
[ -f "${CSVTOOL}" ] || fail "csvtool is not installed, this tool is required by this script"
[ -x "${CSVTOOL}" ] || fail "csvtool is not executable, this tool is required by this script"

if [ ${#} -lt 1 ] ; then
	err "usage: ${SCRIPT} manifest1 [manifest2 manifest3 ... manifestN]"
	exit 1
fi

for n in "${@}" ; do
	do_list "${n}"
done
