//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.05 at 06:21:07 PM CST 
//


package com.armedia.caliente.engine.xml.extmeta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalMetadataFromSQL.t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="externalMetadataFromSQL.t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="query" type="{http://www.armedia.com/ns/caliente/engine}externalMetadataNamesQuery.t"/>
 *         &lt;element name="ignore" type="{http://www.armedia.com/ns/caliente/engine}externalMetadataNamesList.t" minOccurs="0"/>
 *         &lt;element name="transform-names" type="{http://www.armedia.com/ns/caliente/engine}externalMetadataTransformNames.t"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "externalMetadataFromSQL.t", propOrder = {
    "query",
    "ignore",
    "transformDDLNames"
})
public class ExternalMetadataFromSQLT {

    @XmlElement(required = true)
    protected ExternalMetadataNamesQueryT query;
    protected SeparatedValuesList ignore;
    @XmlElement(name = "transform-names", required = true)
    protected TransformDDLNames transformDDLNames;

    /**
     * Gets the value of the query property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalMetadataNamesQueryT }
     *     
     */
    public ExternalMetadataNamesQueryT getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalMetadataNamesQueryT }
     *     
     */
    public void setQuery(ExternalMetadataNamesQueryT value) {
        this.query = value;
    }

    /**
     * Gets the value of the ignore property.
     * 
     * @return
     *     possible object is
     *     {@link SeparatedValuesList }
     *     
     */
    public SeparatedValuesList getIgnore() {
        return ignore;
    }

    /**
     * Sets the value of the ignore property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeparatedValuesList }
     *     
     */
    public void setIgnore(SeparatedValuesList value) {
        this.ignore = value;
    }

    /**
     * Gets the value of the transformDDLNames property.
     * 
     * @return
     *     possible object is
     *     {@link TransformDDLNames }
     *     
     */
    public TransformDDLNames getTransformNames() {
        return transformDDLNames;
    }

    /**
     * Sets the value of the transformDDLNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformDDLNames }
     *     
     */
    public void setTransformNames(TransformDDLNames value) {
        this.transformDDLNames = value;
    }

}
