//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 01:48:42 PM CST 
//


package com.armedia.cmf.engine.xml.importer.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for documentVersion.t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentVersion.t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.armedia.com/ns/cmf/engines/xml/import}sysObject.t">
 *       &lt;sequence>
 *         &lt;element name="historyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="current" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="antecedentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contentSize" type="{http://www.armedia.com/ns/cmf/engines/xml/import}nonNegativeInt.t"/>
 *         &lt;element name="contentHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="contentLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentVersion.t", propOrder = {
    "historyId",
    "version",
    "current",
    "antecedentId",
    "contentSize",
    "contentHash",
    "contentLocation"
})
public class DocumentVersionT
    extends SysObjectT
{

    @XmlElement(required = true)
    protected String historyId;
    @XmlElement(required = true)
    protected String version;
    protected boolean current;
    @XmlElement(required = true)
    protected String antecedentId;
    protected int contentSize;
    @XmlElement(required = true)
    protected byte[] contentHash;
    @XmlElement(required = true)
    protected String contentLocation;

    /**
     * Gets the value of the historyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * Sets the value of the historyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistoryId(String value) {
        this.historyId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the current property.
     * 
     */
    public boolean isCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     */
    public void setCurrent(boolean value) {
        this.current = value;
    }

    /**
     * Gets the value of the antecedentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntecedentId() {
        return antecedentId;
    }

    /**
     * Sets the value of the antecedentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntecedentId(String value) {
        this.antecedentId = value;
    }

    /**
     * Gets the value of the contentSize property.
     * 
     */
    public int getContentSize() {
        return contentSize;
    }

    /**
     * Sets the value of the contentSize property.
     * 
     */
    public void setContentSize(int value) {
        this.contentSize = value;
    }

    /**
     * Gets the value of the contentHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getContentHash() {
        return contentHash;
    }

    /**
     * Sets the value of the contentHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setContentHash(byte[] value) {
        this.contentHash = ((byte[]) value);
    }

    /**
     * Gets the value of the contentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentLocation() {
        return contentLocation;
    }

    /**
     * Sets the value of the contentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentLocation(String value) {
        this.contentLocation = value;
    }

}
